// Search-only community aliases: common RU/CIS nicknames, abbreviations and
// legacy DotA names. Official hero names remain unchanged in the interface.
export const DOTA_HERO_ALIASES: Record<string, string[]> = {
    antimage: ["ам", "am", "антимаг", "магина", "magina"],
    axe: ["акс", "могул", "mogul"],
    bane: ["бейн", "атропос", "atropos"],
    bloodseeker: ["бс", "bs", "сикер", "блудсикер", "стригвир", "strygwyr"],
    crystal_maiden: ["цм", "cm", "цмка", "кристалка", "рылай", "rylai"],
    drow_ranger: ["дровка", "дрова", "тракса", "traxex", "dr"],
    earthshaker: ["еш", "es", "шейкер", "раигор", "raigor"],
    juggernaut: ["джагер", "джаггер", "юра", "юрнеро", "yurnero", "jug"],
    mirana: ["потма", "potm", "принцесса луны"],
    morphling: ["морф", "морфлинг"],
    nevermore: ["сф", "sf", "шадоу финд", "невермор"],
    phantom_lancer: ["пл", "pl", "лансер", "азраил", "azwraith"],
    puck: ["пак", "фея", "дракончик"],
    pudge: ["пудж", "бутчер", "butcher", "мясник", "пиджак"],
    razor: ["разор", "молния"],
    sand_king: ["ск", "sk", "скорпион", "песочник", "криксалис", "crixalis"],
    storm_spirit: ["шторм", "сс", "ss", "райдзин", "raijin"],
    sven: ["свен", "рога", "рогатый", "rogue knight"],
    tiny: ["тини", "камень"],
    vengefulspirit: ["венга", "вендж", "vs", "шадель", "shendelzare"],
    windrunner: ["вр", "wr", "винда", "виндраннер", "аллериа", "alleria"],
    zuus: ["зевс", "зеус"],
    kunkka: ["кунка", "адмирал", "корабль"],
    lina: ["лина", "слеер", "slayer"],
    lion: ["лион", "демонвич", "demon witch"],
    shadow_shaman: ["шаман", "раста", "rhasta"],
    slardar: ["слардар", "рыба", "селедка", "селёдка"],
    tidehunter: ["тайд", "арбуз", "левиафан", "leviathan"],
    witch_doctor: ["вд", "wd", "доктор", "захар"],
    lich: ["лич", "келтуз", "kelthuzad"],
    riki: ["рики", "рикки", "инвиз", "рикимару", "rikimaru"],
    enigma: ["энигма", "черная дыра", "чёрная дыра"],
    tinker: ["тинкер", "боуш", "boush"],
    sniper: ["снайпер", "дед", "кардел", "kardel"],
    necrolyte: ["некр", "некролит", "некрофос", "ротунд", "rotundjere"],
    warlock: ["варлок", "голем", "демнок", "demnok"],
    beastmaster: ["бм", "bm", "бист", "рексар", "rexxar"],
    queenofpain: ["квопа", "qop", "акаша", "akasha", "квина"],
    venomancer: ["веник", "веном", "лешал", "lesale"],
    faceless_void: ["войд", "фв", "fv", "дарктеррор", "darkterror"],
    skeleton_king: ["вк", "wk", "леорик", "leoric", "скелетон кинг", "врайс кинг"],
    death_prophet: ["дп", "dp", "профетка", "кроба", "krobelus"],
    phantom_assassin: ["па", "pa", "фантомка", "мортра", "mortra", "mortred"],
    pugna: ["пугна", "обливион", "oblivion"],
    templar_assassin: ["та", "ta", "темпларка", "ланая", "lanaya"],
    viper: ["вайпер", "гадюка"],
    luna: ["луна", "мунфанг", "moonfang"],
    dragon_knight: ["дк", "dk", "драгон кнайт", "давион", "davion"],
    dazzle: ["дазл", "даззл", "жрец", "shadow priest"],
    rattletrap: ["клок", "клокверк", "clock", "clockwerk"],
    leshrac: ["лешрак", "леш", "tormented soul"],
    furion: ["фура", "фурион", "нп", "np", "профет", "nature prophet"],
    life_stealer: ["гуль", "найкс", "naix", "лифстилер", "ls"],
    dark_seer: ["дс", "ds", "дарк сир", "ишкафель", "ishkafel"],
    clinkz: ["клинкс", "боник", "bone", "костяной"],
    omniknight: ["омник", "омни", "пурист", "purist"],
    enchantress: ["энча", "коза", "дриада", "аиушта", "aiushtha"],
    huskar: ["хускар", "хуск"],
    night_stalker: ["баланар", "balanar", "нс", "ns", "найт сталкер"],
    broodmother: ["бруда", "паучиха", "паук"],
    bounty_hunter: ["бх", "bh", "баунти", "гондар", "gondar"],
    weaver: ["вивер", "жук", "анубсеран", "anubseran"],
    jakiro: ["джакиро", "джакир", "тхд", "thd", "двухголовый"],
    batrider: ["бат", "бэтрайдер", "летучка"],
    chen: ["чен", "зоопарк"],
    spectre: ["спектра", "меркуриал", "mercurial"],
    doom_bringer: ["дум", "люцифер", "lucifer", "думбрингер"],
    ancient_apparition: ["аа", "aa", "аппарат", "калдр", "kaldr"],
    ursa: ["урса", "медведь", "ульфсаар", "ulfsaar"],
    spirit_breaker: ["бара", "баратрум", "barathrum", "сб", "sb", "корова"],
    gyrocopter: ["гиро", "вертолет", "вертолёт", "коптер"],
    alchemist: ["алхимик", "алхим"],
    invoker: ["инвокер", "вокер", "карл", "kael", "каэль"],
    silencer: ["сало", "сайленсер", "нортром", "nortrom"],
    obsidian_destroyer: ["од", "od", "оутворлд", "дестроер", "харбрингер", "обсидиан"],
    lycan: ["ликан", "волк", "бейнхаллоу", "banehallow"],
    brewmaster: ["брю", "панда", "пивовар", "мангикс", "mangix"],
    shadow_demon: ["шд", "sd", "демон", "эрэдар", "eredar"],
    lone_druid: ["лд", "ld", "друид", "медведь", "силабир", "syllabear"],
    chaos_knight: ["цк", "ck", "хаос", "несаж", "nessaj"],
    meepo: ["мипо", "геомансер", "гео"],
    treant: ["трент", "дерево", "рутфеллен", "rooftrellen"],
    ogre_magi: ["огр", "огр маг", "агаг", "aggron"],
    undying: ["андаинг", "зомби", "дирдж", "dirge"],
    rubick: ["рубик", "рубен", "гранд магус"],
    disruptor: ["дизраптор", "диз", "тралл", "thrall"],
    nyx_assassin: ["никс", "жук", "анубарак", "anubarak", "неруб"],
    naga_siren: ["нага", "сирена", "слизис", "slithice"],
    keeper_of_the_light: ["котл", "kotl", "дед", "эзалор", "ezalor"],
    wisp: ["ио", "io", "висп", "шар"],
    visage: ["визаж", "гаргулья", "некролик", "necrolic"],
    slark: ["сларк", "рыба", "мурлок"],
    medusa: ["медуза", "горгона", "gorgon"],
    troll_warlord: ["тролль", "троляка", "джахракал", "jah'rakal"],
    centaur: ["кентавр", "кент", "варраннер", "warrunner", "бредварден"],
    magnataur: ["магнус", "магнатаур", "магн"],
    shredder: ["тимбер", "тимберсоу", "шреддер", "пила"],
    bristleback: ["бристл", "бб", "bb", "еж", "ёж", "ригварл", "rigwarl"],
    tusk: ["таск", "туск", "морж", "имир", "ymir"],
    skywrath_mage: ["скай", "петух", "скаймаг", "драконус", "dragonus"],
    abaddon: ["абаддон", "абба", "лорд авернус", "avernus"],
    elder_titan: ["титан", "ет", "et", "таурен", "tc"],
    legion_commander: ["легионка", "лк", "lc", "тресдин", "tresdin"],
    ember_spirit: ["эмбер", "огненный спирит", "син", "xin"],
    earth_spirit: ["земеля", "земля", "каолин", "kaolin"],
    abyssal_underlord: ["андерлорд", "питлорд", "пит", "азгалор", "azgalor"],
    terrorblade: ["тб", "tb", "террор", "soul keeper"],
    phoenix: ["феникс", "птица", "цыпа"],
    oracle: ["оракл", "оракул", "нераф", "nerif"],
    winter_wyvern: ["виверна", "виверн", "вв", "ww", "аурот", "auroth"],
    arc_warden: ["арк", "арчик", "зет", "zet", "aw"],
    monkey_king: ["мк", "mk", "манки", "обезьяна", "сунь укун", "wukong"],
    dark_willow: ["виллоу", "фея", "миреска", "mireska", "dw"],
    pangolier: ["панго", "броненосец", "донте", "donte"],
    grimstroke: ["грим", "гримстроук", "художник"],
    mars: ["марс", "бог войны"],
    void_spirit: ["войд спирит", "вс", "vs", "фиолетовый спирит", "иней", "inai"],
    snapfire: ["бабка", "снапка", "снапфаер", "бабушка"],
    hoodwink: ["белка", "худвинк", "белочка"],
    dawnbreaker: ["дб", "db", "донбрейкер", "валора", "valora"],
    marci: ["марси", "марча"],
    primal_beast: ["пб", "pb", "праймал", "зверь", "динозавр"],
    muerta: ["муэрта", "мерта", "мексиканка"],
    ringmaster: ["рингмастер", "циркач", "кукловод"],
    kez: ["кез", "попугай", "птица"],
    largo: ["ларго", "лягушка", "жаба", "бард", "frog", "toad"],
    techies: ["течка", "минер", "минёр", "течис", "гоблины"],
};
